version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./billing.db
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_BACKEND_URL=http://host.docker.internal:8000
    depends_on:
      - backend
